### ISSUE TITLE
Bad slurp with oq, yaml-input and multiple files

### ISSUE THREAD

**Issue by blurayne** [Blacksmoke16/oq#70]
a.yaml:
```yaml
include:
 - project: 'my-group/my-project'
   file: '/templates/.gitlab-ci-template.yml'
a: ["here", "i", "am"]
```

b.yaml:
```yaml
include:
  - remote: 'https://gitlab.com/example-project/-/raw/master/.gitlab-ci.yml'
b: {"greet": "from b with love"}
```

Correct behavior:

We use oq to first convert yaml to json then use pure jq

```bash
$ for y in a.yaml b.yaml; do oq --input=yaml . $y > ${y%.*}.json; done
$ jq -s . a.json b.json
[
  {
    "include": [
      {
        "project": "my-group/my-project",
        "file": "/templates/.gitlab-ci-template.yml"
      }
    ],
    "a": [
      "here",
      "i",
      "am"
    ]
  },
  {
    "include": [
      {
        "remote": "https://gitlab.com/example-project/-/raw/master/.gitlab-ci.yml"
      }
    ],
    "b": {
      "greet": "from by with love"
    }
  }
]
```

Now what happens here?

```bash
$ oq --input=yaml -s . a.yaml b.yaml 
[
  {
    "include": [
      {
        "remote": "https://gitlab.com/example-project/-/raw/master/.gitlab-ci.yml"
      }
    ],
    "a": [
      "here",
      "i",
      "am"
    ],
    "b": {
      "greet": "from b with love"
    }
  }
]
```
